# Generated by Django 4.1.3 on 2022-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('birth_date', models.DateField()),
                ('shift', models.CharField(choices=[('1st', 'Frist Shift'), ('2nd', 'Second Shift')], max_length=4)),
                ('session', models.CharField(max_length=15)),
            ],
        ),
    ]
